server:
  address: 127.0.0.1
  port: 8081
  contextPath: /vitalsport/photos
management:
  port: 8082
  address: 127.0.0.1
vitalsport:
  secretKey: verySecretKey
multipart:
  maxFileSize: 1024KB
  maxRequestSize: 1024KB